[project]
name = "nerf_tools"
version = "0.1.0"  # You can specify a version here
description = "Description of your project"
dependencies = []  # Add dependencies if there are any

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

